import Navbar from "@/components/Navbar";
import "./globals.css";
import { Sora } from "next/font/google";

const inter = Sora({ subsets: ["latin"] });

export const Wrapper = ({ children }: { children: React.ReactNode }) => {
  return <div className="max-w-7xl mx-4 md:mx-auto">{children}</div>;
};



export const metadata = {
  title: "Ecommerce-Sanity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
          {/* <Navbar /> */}
          {children}
        </Wrapper>
      </body>
    </html>
  );
}
